### ISSUE TITLE
how do i install this?

### ISSUE THREAD

**Issue by zoharargaman** [lolo101/MsgViewer#1]

**Comment by lolo101** [comment]
There is no installation. The application is a runnable jar.

So just download a release : https://github.com/lolo101/MsgViewer/releases

And run the command specified in the README : `java -jar msgviewer.jar` (you need to have **java** installed)

Do not hesitate to ask if you need more details.

**Comment by lolo101** [comment]
Did you downloaded a release ? For instance [release 1.2.0](https://github.com/lolo101/MsgViewer/releases/download/v1.2.0/msgviewer.jar), that's a jar file.

However you can also build a jar file from the sources with the following command (you need **Maven** installed on your system) :
Be sure to be in the base directory (the one containing the README.md)
```
mvn package
```
The jar should be generated as *MSGViewer/target/msgviewer.jar*.
Then just enter the command
```
java -jar MSGViewer/target/msgviewer.jar
```
And the GUI should display.

Is it working better ?

**Comment by zoharargaman** [comment]
Niceness! thank you!

initially somehow i downloaded a zip file and not jar.

anyway its great. i added a Bash to my desktop to load it up as i cant launch like a regular app. do you have any better idea? 

anyway it's great thank you
