### ISSUE TITLE
Class cast Exception while opening msg file

### ISSUE THREAD

**Issue by minirich** [lolo101/MsgViewer#100]
I got an msg file with a single .jpg as an attachement, and when I tried to open it i got an error:
"class [B cannot be cast do class java.lang.String([B and java.lang.String are in module Java.base of loader 'bootstrap')
That is the msg file (remove the .txt) for replication [Poss fehlender Vertrag (1).msg.txt](https://github.com/lolo101/MsgViewer/files/8708901/Poss.fehlender.Vertrag.1.msg.txt)
<img width="460" alt="Snapshot_Error_classcast_MsgViewer" src="https://user-images.githubusercontent.com/815592/168829929-ff4fd605-be09-4703-b96a-c5cc797b1090.png">

**Comment by lolo101** [comment]
Hi @minirich and thank you for the report and the very helpful example !

I start investigating the issue

**Comment by lolo101** [comment]
Hi @minirich please give a try to release 1.8.5 and reopen the issue if the problem persists ;)

**Comment by minirich** [comment]
Works like a charm.
Thanks for the prompt fix
