### ISSUE TITLE
An error occured : Unclosed block

### ISSUE THREAD

**Issue by skalg** [lolo101/MsgViewer#11]
I'm getting this error when i'm trying to open a specific msg file. " An error occured : Unclosed block "

The msg file is working with Outlook. Let me know if you need anything to help.

Thanks

**Comment by lolo101** [comment]
Hi @skalg, is it possible to have the msg file to reproduce the issue ? You may send it privately to my email you can find in the git log ;)

**Comment by lolo101** [comment]
In addition, is there any stack trace in the console ?

**Comment by lolo101** [comment]
Looks like you have an issue with the RTF content of your msg.
Is it possible to share the RTF content in order to reproduce the issue ?

**Comment by skalg** [comment]
I've lost the msg file that gave me this error. Sorry i'll reopen if i get it back. Thank you

**Comment by lolo101** [comment]
@skalg sent me a .msg file that reproduce the issue.
Exception occurs in CSS parser, so maybe an issue with CSS instead of RTF ? Investigating...

**Comment by lolo101** [comment]
This message fragment looks suspicious :
```
 /* List Definitions */
 @list l0
	{mso-list-id:1250697184;
	 mso-list-type:hybrid;
	 mso-list-template-ids:943894750 202113025 202113027 202113029 202113025 202113027 202113029 202113025 202113027 202113029;}
 @list l0:level1
	{mso-level-number-format:bullet;
	 mso-level-text: </style> <!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext="edit" spidmax="1026" />
 </xml><![endif]--> <!--[if gte mso 9]><xml>
 <o:shapelayout v:ext="edit">
 <o:idmap v:ext="edit" data="1" />
 </o:shapelayout></xml><![endif]-->
 </head>
```
