### ISSUE TITLE
Should/Could this work for oft as well?

### ISSUE THREAD

**Issue by TryTryAgain** [lolo101/MsgViewer#112]
I wasn't able to find much on the topic of msg vs oft...

https://stackoverflow.com/questions/7957827/is-there-a-difference-between-the-outlook-msg-and-oft-file-formats

But what I did do was try and use MsgViewer without changing anything and it failed, but then I copied the file `cp test.oft test.msg` and tried again and then it worked flawlessly and made me very happy 👍 ...what a great app, have loved it for MSGtoEML for some time and was very happy to learn it supported OFT as well.

I'm using an Automator script/app that allows me to drag/drop the file onto the MSGtoEML app icon on my dock and automatically convert ... vs. needing to fiddle with the CLI or open the GUI:

MSGtoEML Automator app (run shell script /bin/bash):
```
for f in "$@"; do
	DIR="$(dirname "${f}")" ; FILE="$(basename "${f}")"
	filename="${FILE%.*}"
	java -jar /usr/local/bin/msgviewer.jar -msg2eml "$f" "$DIR/$filename.eml"
done
```

To save people from needing to cp .oft to .msg before running the program, I created [this pull request](https://github.com/lolo101/MsgViewer/pull/111) I hope you will consider merging. Thanks for the great app!

**Comment by lolo101** [comment]
Hi @TryTryAgain and thanks for using MsgViewer and for this great contribution!

I didn't even know the OFT extension. If the format is the same as MSG I would gladly accept the pull request.

Indeed the Codacy error is non-blocking :)
