### ISSUE TITLE
Is there a license for the project?

### ISSUE THREAD

**Issue by andipabst** [lolo101/MsgViewer#113]
Thanks for continuing this great and helpful project! 

I was looking into packaging it as a [Homebrew](https://brew.sh/) formula, to ease the installation.
But all projects included in the homebrew-core repository need to specify their license (see [the Formula Cookbook](https://docs.brew.sh/Formula-Cookbook#fill-in-the-license) for more information).

But I could not find any license information in the project, so I wanted to ask, if the project is published under a specific open source license?

**Comment by lolo101** [comment]
You are right @andipabst, a license was indeed missing.

I just added the Unlicense. Hope it's ok for the homebrew-core repository?

**Comment by lolo101** [comment]
@andipabst don't hesitate to reopen if the license doesn't suit your need
