### ISSUE TITLE
Set RTF/Text via parameter

### ISSUE THREAD

**Issue by mik0001** [lolo101/MsgViewer#143]
The option "RTF/Text" should be adjustable via parameter, e.g. :    -text 
If this parameter is not set, "RTF" is default, if possible.

**Comment by lolo101** [comment]
Hi @mik0001 and thank you for your suggestion

However, could you be more specific? Are you talking about the possibility to converting a message that has an RTF body to a plain text message?

**Comment by mik0001** [comment]
Yes. I just want to have the Radiofield "Text" on the bottom of the frame as default on program-start with a given msg-file, when parameter "-text" is additionally set.

**Comment by lolo101** [comment]
Yes, that is possible to do. Could you tell me what is your use case?

I don't think it is worth adding a new CL option just to save a click. Hence I suppose you have a more constrained use case and I need to understand it to help you best.

**Comment by ThomasChr** [comment]
Good morning lolo101, 

let me explain that!
mik0001 is a colleque of mine. We are a small company providing ERP solutions for our customers. Our customers are used to highly customized software and so they have sometimes strange wishes :-)

In this case we're starting the msgviewer right from the command line with a msg-File. That works just fine but now the customers wants the Text Version to display at startup, not the RTF Version (I have no idea why...).

This isn't a big problem for us to just put in a new parameter setting the default start view. We can do that in our ERP system and if you like I can do that in the msgviewer code and provide a PR for you. Would that work for you? Any better ideas?

Thomas

**Comment by ThomasChr** [comment]
Oh, I see there is some kind of config parameter for that?
![image](https://user-images.githubusercontent.com/13014163/193764276-bc3b342f-fe97-4b1f-b767-89b8fd0f40a1.png)
I'll check that!

**Comment by ThomasChr** [comment]
I think that will work for us. Adding the following:
![image](https://user-images.githubusercontent.com/13014163/193765607-a6480888-3920-4967-812e-7dd8205eb9be.png)
to file:
`C:\Users\tchristlieb\MSGViewer\MSGViewer.properties`
does the trick!

I'm pretty sure we can add that to our application.

**Comment by ThomasChr** [comment]
Okay, there is still a problem with the config file - it's only on a per user base.
If you have a system with many users that won't cut it.

So we need to add a start parameter or do you have a better idea?

**Comment by lolo101** [comment]
Hi @ThomasChr and thank you very much for the explanation :slightly_smiling_face: 

I'm very honored to see MsgViewer used in a professional context.

I think this feature hardly deserves a command line switch and I'd rather implement a fallback system from the local config to a global config. I'll look into this.

Meanwhile, if you need this feature quickly you can of course implement it and propose a PR, I'd gladly consider it

**Comment by lolo101** [comment]
This is an ad-hoc development. You don't need to bother with `isYes` and `map(s->"yes")`. You may just do something like
```java
boolean rtfFormat = StringUtils.isYes(root.getSetup().getLocalConfig("RTFFormat", "yes"))
        && Stream.of(root.getStartupArgs()).noneMatch(isEqualTo(CLI_STARTUP_TEXT_VIEW));
```
That would be a very acceptable workaround waiting for a global config

Is it ok for you?

**Comment by ThomasChr** [comment]
Absolutely!
I will code the PR tomorrow!
Thanks for your help!

**Comment by ThomasChr** [comment]
I'm not very good at patience, so here's the PR :-)

**Comment by lolo101** [comment]
It's merged 👍

**Comment by ThomasChr** [comment]
Thanks a lot!
Should we close this Issue or leave it open?

**Comment by lolo101** [comment]
Let's close it as your PR solves the problem stated. I'll open a new one to improve the configuration

**Comment by ThomasChr** [comment]
Would be glad to help with the new one if I can!
