### ISSUE TITLE
openjdk basic requirement

### ISSUE THREAD

**Issue by kintaro1981** [lolo101/MsgViewer#195]
Hello,
I converted in .exe with launch4j to distribuite it to our Win10 clients.

I would like to reduce the size of the openjdk directory I need to bundle with it (I can't install openjdk).
Is it possible to delete from the openjdk directory what is not used from msgviewer? If yes, what can I delete?

**Comment by lolo101** [comment]
Hi @kintaro1981 !

Are you talking about which JDK modules are required?

I just pushed module-info files, so I believe you can now extract just what you need from the JDK modules

Does it answer your question?

**Comment by lolo101** [comment]
For your information, here is the module dependency graph:
![msgviewer](https://github.com/lolo101/MsgViewer/assets/555864/e7ec6170-87af-4a10-8cf6-2bd0cf38668f)
