### ISSUE TITLE
I use MsgViewer to convert msg to html, but it has rtf code in the html for example cea2c8edd1c5bada

### ISSUE THREAD

**Issue by whaozl** [lolo101/MsgViewer#2]

**Comment by lolo101** [comment]
I don't understand the issue...
Do you mean RTF like in [Rich Text Format](https://en.wikipedia.org/wiki/Rich_Text_Format) ?
Or do you mean there are badly encoded characters in the rendered HTML ?

Could you provide an example with a MSG causing the issue and the expected HTML ?

**Comment by whaozl** [comment]
yeah, and [outlook-message-parser](https://github.com/bbottema/outlook-message-parser/issues/3) help me solove this problem. but MsgViewer also has this problem.
link：https://pan.baidu.com/s/1H3FZswvrCRMem4d_zGIyyQ password：dl9s

**Comment by lolo101** [comment]
Ok thanks, I could reproduce your issue.
I can see many strange stuff like `<span lang=EN-US style='font-family:"cea2c8edd1c5bada",sans-serif;color:black'>`
I see there has been a nice investigation at https://github.com/bbottema/outlook-message-parser/issues/3 I'm going to read it carefully. As far as I understand it's related to missing DBCS support.

**Comment by lolo101** [comment]
Last commit fixed detection of escaped hexa character in RTF body.

However that does not fix this issue since you now have unicode FFFD character instead of a string of hexa, but still that's not the expected text.

**Comment by lolo101** [comment]
commit 06737b1ecb756c64d4679657a8c1de10a48b5cc3 fixed the issue :)
I'm going to release version 1.6.0
![RTF_fixed](https://user-images.githubusercontent.com/555864/56955189-fee4d780-6b40-11e9-9426-44aaf980a384.png)

**Comment by whaozl** [comment]
This is a very great things. thank you very much.
