### ISSUE TITLE
different attachments with the same name result in same file contens

### ISSUE THREAD

**Issue by datsteves** [lolo101/MsgViewer#205]
Hello, 
Me again.
Now we got an email on our hands even, I wondered how this can happen naturally.
In this case, we have an email with three different images (which probably can be any filetype), but all have the same name.
This then results that the actual content of those files that we get is always the same, even though the contentId and filesize are different.

## Test File

[msg and eml.zip](https://github.com/lolo101/MsgViewer/files/11956687/msg.and.eml.zip)

## Screenshots

<img width="1142" alt="image" src="https://github.com/lolo101/MsgViewer/assets/31381383/3257a04f-cfb4-460e-9651-cbf6c97cc1d9">

![image](https://github.com/lolo101/MsgViewer/assets/31381383/84a55dd6-c40c-4808-a5fa-7b8814af885d)

----
<img width="306" alt="image" src="https://github.com/lolo101/MsgViewer/assets/31381383/19fcd739-70d0-48be-9480-9603ec2ff7d1">

This data from this screenshot comes actually from another parser (that is far too unreliable for anything with text), but shows the file sizes correctly :)

**Comment by lolo101** [comment]
Hi @datsteves and thank you for this interesting report!

Actually, thumbnails are stored in a temporary directory with the same filename as the original attachment. If several attachments have the same name, the last thumbnail overwrites the previous ones.

Maybe we could use some other property as the filename like the `pidContentId` for instance or some random name and keep track of that name in the Attachment object

I'll look into this!

**Comment by lolo101** [comment]
Hi @datsteves,

Could you confirm that commit https://github.com/lolo101/MsgViewer/commit/d4a2a9962f5bc579759f7fe3c4a0efda224e6308 fixes the issue?

**Comment by datsteves** [comment]
hey @lolo101 
yes i can confirm that the build from the current master fixes this issue :)
thank you very much ^^
