### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by AndresGG** [lolo101/MsgViewer#236]
Hi,

In the Version.java file it  says '1.10', should it be '1.8.8'?

**Comment by lolo101** [comment]
Hi @AndresGG !

Yes that Version.java is quite nonsense :smiley: 
I should just delete it but it never went up my todo list.

Having an open issue will stimulate me :wink:

**Comment by lolo101** [comment]
Hello @AndresGG 

The version should now be read from the manifest file and the same as the maven artifact.
Thank you for the challenge :wink:
