### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by skalg** [lolo101/MsgViewer#4]
I'm getting the following error message

> Es ist ein Fehler aufgetreten: Encountered
> "ri" at line 181, column 21 }.
> Was expecting
> one of:
> <EOF>
> "{" ...

**Comment by lolo101** [comment]
Hi @skalg and thank you for using the project.

It looks like you are parsing some invalid RTF input.

Could you explain how to reproduce the error and ideally provide an example file ?

**Comment by lolo101** [comment]
Ok I could manage to reproduce the issue.

I'm working on it...

**Comment by lolo101** [comment]
I believe these are padding bytes that should be dropped.
See : https://poi.apache.org/apidocs/4.0/org/apache/poi/hmef/CompressedRTF.html#decompress-java.io.InputStream-java.io.OutputStream-

**Comment by lolo101** [comment]
@skalg please don't hesitate to try [v1.3.0](https://github.com/lolo101/MsgViewer/releases/tag/v1.3.0) and reopen this issue if error persist

**Comment by skalg** [comment]
It's working !! Thank you !!
