### ISSUE TITLE
To: and From: missing

### ISSUE THREAD

**Issue by LGMAM** [lolo101/MsgViewer#48]
Hi,
I am using a simple EML file to test the conversion to msg file, but it seems that To: and From: are missing after the conversion.

Content-Transfer-Encoding: quoted-printable
To: example@gmail.com
From: Foo <foo@example.com>
Subject: test
Content-Type: text/plain; charset="utf-8"
Mime-Version: 1.0

=C2=A1Test!

Using outlook 2019 I am getting this

![msg_conversion](https://user-images.githubusercontent.com/3864307/127299448-221e9a46-b1d6-4bf6-8fb9-79d83487020f.png)

Any hint ?

Thanks

**Comment by lolo101** [comment]
Hi @LGMAM and thank you for this report !
I'll investigate on this issue.

**Comment by lolo101** [comment]
Hi ! After some tests, the "From" element seems ok.
The "To" may be problematic because since there is no name (only email address) MSGViewer inserts a blank name (this needs to be fixed).
Your email client seems configured to display the name only, so "To" shows nothing and "From" shows "Foo".

**Comment by lolo101** [comment]
Ok I reproduced your screen with an Office client and converted the .eml with MSGViewer and also with the Office client to compare the structure of the .msg files.
I'll work toward improving MSGViewer conversion to better match the "official" one

**Comment by lolo101** [comment]
Ok. All the PidTagSentRepresenting* properties are missing whereas they are mandatory and should reflect the PidTagSender* properties

**Comment by lolo101** [comment]
Hi @LGMAM,

Is it possible for you to build the latest sources and check if the bug is fixed ?

Many thanks
