### ISSUE TITLE
In russian locale Windows I can`t get attachment file with cyrillic name.

### ISSUE THREAD

**Issue by bootcd** [lolo101/MsgViewer#5]
File with cyrillic name saves to  \users\appdata......\tmp\filename.doc (for examp) but can`t open it.
I have this output in cmd:

2019-04-02 14:29:12,872 INFO  (ViewerPanel.java:665): <a href="file://%D0%9A%D0%
B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B0+%D0%A2%D0%94+%D0%90%D0%BA%D1%82.doc"> app
lication/octet-stream
2019-04-02 14:29:12,872 INFO  (ViewerPanel.java:665): <a href="file://Eaton+12CB
350.pdf"> application/pdf
2019-04-02 14:29:23,008 INFO  (ViewerPanel.java:441): file://%D0%9A%D0%B0%D1%80%
D1%82%D0%BE%D1%87%D0%BA%D0%B0+%D0%A2%D0%94+%D0%90%D0%BA%D1%82.doc
2019-04-02 14:29:23,008 INFO  (ViewerHelper.java:242): opening ¶р®™юҐър T- Lъ™.d
oc
2019-04-02 14:29:23,008 INFO  (ViewerPanel.java:495): opening: C:\Users\sysadmin
\AppData\Local\Temp\2\xxxx7217742277775047212.tmp\¶р®™юҐър T- Lъ™.doc
2019-04-02 14:29:23,008 DEBUG (ViewerPanel.java:499): shell exec returned: 0

**Comment by bootcd** [comment]
BTW, In russian locale MacOS prog works good!

**Comment by lolo101** [comment]
Hi @bootcd and thank you for your interest in the project.

I see from the log you provided that the "open" operation was delegated to the system.

Did you get any message dialog ?
Are you able to open the file "Карточка+ТД+Акт.doc" (is it its correct name ?) by double-clicking it in Windows ?

**Comment by bootcd** [comment]
Hi,lolo101
Yes i can open this file in Windows by duobleclick. It may be opened by MS Word or etc without troubles.
When i use Msgviewer, i see attachments links in window. Whe i clicking link to english named attachment file, it opens with assotiated program. I have log in cmd and last string like that:

<code>2019-04-05 14:14:58,054 DEBUG (ViewerPanel.java:499): shell exec returned: 1</code>

But when i do this with cyrillic named attchment file link, there nothing happens. And i see that log in cmd window has same string but with <code>shell exec returned: 0</code>

**Comment by lolo101** [comment]
Hi ! Feel free to use [release 1.4.0](https://github.com/lolo101/MsgViewer/releases/tag/msgviewer-1.4.0) and tell me if problem persists
