### ISSUE TITLE
Replicated jpeg attachment

### ISSUE THREAD

**Issue by skalg** [lolo101/MsgViewer#59]
Not always, but sometimes, the first image is replicated for all the other one.
The preview is replicated and also when the image is selected. We are not able to see the other images.

![2021-10-06_15-47-13 copy (1)](https://user-images.githubusercontent.com/3055793/136272916-8f0357c9-aaf8-4878-b427-e63649531aad.png)

**Comment by lolo101** [comment]
Hi ! Can you confirm the bug is fixed with the latest sources ? You need to build the project on your own. Is it ok for you ?

**Comment by skalg** [comment]
> Hi ! Can you confirm the bug is fixed with the latest sources ? You need to build the project on your own. Is it ok for you ?

Yes it's working. Thank you !
