### ISSUE TITLE
Compile MsgViewer on Windows 10

### ISSUE THREAD

**Issue by novaklu** [lolo101/MsgViewer#78]
Hello
I'm trying to compile MsgViewer on Windows 10 and I'm getting this error message. When compiling on Ubuntu 20.04 I do not get this message. My goal is to create an installation for Windows with InnoSetup. Creating the required path "file:/tmp/xxx.tmp/" on Windows did not help. I am using Apache NetBeams 12.5 and Java amazon-corretto-11.0.13.8.1-windows-x64.

Can I ask for advice on where to look for the source of the difficulty?

-------------------------------------------------------------------------------
Test set: net.sourceforge.MSGViewer.PrepareImagesTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.554 s <<< FAILURE! - in net.sourceforge.MSGViewer.PrepareImagesTest
net.sourceforge.MSGViewer.PrepareImagesTest.should_replace_images_sources_with_relative_path  Time elapsed: 1.507 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <<img src="file:/tmp/xxx.tmp/content-location-2"></img>> but was: <<img src="file:/C:/tmp/xxx.tmp/content-location-2"></img>>
	at net.sourceforge.MSGViewer.PrepareImagesTest.should_replace_images_sources_with_relative_path(PrepareImagesTest.java:37)

net.sourceforge.MSGViewer.PrepareImagesTest.should_replace_images_sources_with_content_id  Time elapsed: 0.005 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <<img src="file:/tmp/xxx.tmp/long-filename-1"></img>> but was: <<img src="file:/C:/tmp/xxx.tmp/long-filename-1"></img>>
	at net.sourceforge.MSGViewer.PrepareImagesTest.should_replace_images_sources_with_content_id(PrepareImagesTest.java:27)

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------

--- maven-surefire-plugin:3.0.0-M5:test (default-test) @ msgviewer ---
file.encoding cannot be set as system property, use <argLine>-Dfile.encoding=...</argLine> instead

Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project msgviewer: There are test failures.

Please refer to C:\Users\novakl1\OneDrive - Colas\Dokumenty\MsgViewer\MSGViewer\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

After correcting the problems, you can resume the build with the command
  mvn <args> -rf :msgviewer

Thank you in advance for your help novaklu

**Comment by lolo101** [comment]
Hello @novaklu and thank you for your investment in MsgViewer :)

Unfortunately, the trace you posted doesn't display correctly: "expected: <> but was: <>" probably because the values contain brackets that are always problematic when shared on the web :)

Since you mentioned the path "file:/tmp/xxx.tmp" which is the default temporary path on Linux I suspect the test isn't consistently repeatable on different OS. It needs to be fixed to be system-independant.

**Comment by novaklu** [comment]
Hello
Thank you for your quick response. I apologize for the incomplete question. 
I have run new tests and am sending clarifications.

-------------------------------------------------------
LOGS
------------------------------------------------------

--- maven-surefire-plugin:3.0.0-M5:test (default-test) @ msgviewer ---
file.encoding cannot be set as system property, use \<argLine\>-Dfile.encoding=...\</argLine\> instead

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.949 s \<\<\< FAILURE! - in net.sourceforge.MSGViewer.PrepareImagesTest
net.sourceforge.MSGViewer.PrepareImagesTest.should_replace_images_sources_with_relative_path  Time elapsed: 1.9 s  \<\<\< FAILURE!
org.opentest4j.AssertionFailedError: expected: \<\<img src="file:/tmp/xxx.tmp/content-location-2">\</img\>\> but was: \<\<img src="file:/C:/tmp/xxx.tmp/content-location-2/\>\</img\>\>
	at net.sourceforge.MSGViewer.PrepareImagesTest.should_replace_images_sources_with_relative_path(PrepareImagesTest.java:37)

net.sourceforge.MSGViewer.PrepareImagesTest.should_replace_images_sources_with_content_id  Time elapsed: 0.01 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: \<\<img src="file:/tmp/xxx.tmp/long-filename-1"\>\</img\>\> but was: \<\<img src="file:/C:/tmp/xxx.tmp/long-filename-1/"\>\</img\>\>
	at net.sourceforge.MSGViewer.PrepareImagesTest.should_replace_images_sources_with_content_id(PrepareImagesTest.java:27)


Results:

Failures: 
  PrepareImagesTest.should_replace_images_sources_with_content_id:27 expected: \<\<img src="file:/tmp/xxx.tmp/long-filename-1"\>\</img\>\> but was: \<\<img src="file:/C:/tmp/xxx.tmp/long-filename-1/"\>\</img\>\>
  PrepareImagesTest.should_replace_images_sources_with_relative_path:37 expected: \<\<img src="file:/tmp/xxx.tmp/content-location-2"\>\</img\>\> but was: \<\<img src="file:/C:/tmp/xxx.tmp/content-location-2/"\>\</img\>\>


Results:

Failures: 
  PrepareImagesTest.should_replace_images_sources_with_content_id:27 expected: "\<"img src="file:/tmp/xxx.tmp/long-filename-1"\>"\</img"\> but was: "\<img src="file:/C:/tmp/xxx.tmp/long-filename-1/"\>"\</img"\>
  PrepareImagesTest.should_replace_images_sources_with_relative_path:37 expected: \<img src="file:/tmp/xxx.tmp/content-location-2"\>\</img\> but was: \<img src="file:/C:/tmp/xxx.tmp/content-location-2/"\>\</img\>


Sincerely

**Comment by lolo101** [comment]
For a quick workaround, you can just add `@Disabled` annotation on `PrepareImagesTest` as it may take some time for me to find a proper way to inject the filesystem into PrepareImages to make the test repeatable

**Comment by lolo101** [comment]
@novaklu could you please check and reopen this issue if needed?

Thanks!
