### ISSUE TITLE
Feature Request : Add print option

### ISSUE THREAD

**Issue by skalg** [lolo101/MsgViewer#8]
Love this software, would it be hard to add a print option ? 

That's the only thing missing for me.

Thank you for your fixes and to keeping it updated.

**Comment by lolo101** [comment]
Hi @skalg and thank you for your continuous interest in the projet ;)
Indeed that would be a useful option and the JDK has solutions for this feature.
I'll look into this

**Comment by skalg** [comment]
Thank you !! :)
